apiVersion: networkfunction.nephio.io/v1alpha1
kind: Upf
metadata:
  name: free5gc-upf-1
  namespace: default
spec:
  parent: upf-class-1
  namespace: upf-1
  clustername: nephio-edge-1
  n3:
    endpoints:
    - ipv4Addr:
      - "10.10.5.3/24"
      gwv4addr: "10.10.5.1"
  n4:
    endpoints:
    - ipv4Addr:
      - "192.168.100.3/24"
      gwv4addr: "192.168.100.1"
  n6:
    endpoints:
      internet:
        ipendpoints:
          ipv4Addr:
          - "10.20.3.3/24"
          gwv4addr: "10.20.3.1"
        ipaddrpool: "10.20.3.0/24"
