# permissions for end users to edit nfnetworkresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfnetworkresource-editor-role
rules:
- apiGroups:
  - resources.nephio.io
  resources:
  - nfnetworkresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.nephio.io
  resources:
  - nfnetworkresources/status
  verbs:
  - get
