# permissions for end users to view repoconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repoconfig-viewer-role
rules:
- apiGroups:
  - baseconfig.nephio.io
  resources:
  - repoconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - baseconfig.nephio.io
  resources:
  - repoconfigs/status
  verbs:
  - get
