# permissions for end users to view nfdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfdeployment-viewer-role
rules:
- apiGroups:
  - networkfunction.nephio.io
  resources:
  - nfdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networkfunction.nephio.io
  resources:
  - nfdeployments/status
  verbs:
  - get
