# permissions for end users to edit nfdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfdeployment-editor-role
rules:
- apiGroups:
  - networkfunction.nephio.io
  resources:
  - nfdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networkfunction.nephio.io
  resources:
  - nfdeployments/status
  verbs:
  - get
