# permissions for end users to view nfresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfresource-viewer-role
rules:
- apiGroups:
  - networkfunction.nephio.io
  resources:
  - nfresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networkfunction.nephio.io
  resources:
  - nfresources/status
  verbs:
  - get
