# permissions for end users to view upfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upf-viewer-role
rules:
- apiGroups:
  - networkfunction.nephio.io
  resources:
  - upfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networkfunction.nephio.io
  resources:
  - upfs/status
  verbs:
  - get
