# permissions for end users to edit upfclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upfclass-editor-role
rules:
- apiGroups:
  - networkfunction.nephio.io
  resources:
  - upfclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networkfunction.nephio.io
  resources:
  - upfclasses/status
  verbs:
  - get
