# permissions for end users to view upfclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upfclass-viewer-role
rules:
- apiGroups:
  - networkfunction.nephio.io
  resources:
  - upfclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networkfunction.nephio.io
  resources:
  - upfclasses/status
  verbs:
  - get
