//
//Copyright 2024 The Nephio Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: nfdeployment.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NFDeployment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiVersion string `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace  string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *NFDeployment) Reset() {
	*x = NFDeployment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nfdeployment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NFDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NFDeployment) ProtoMessage() {}

func (x *NFDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_nfdeployment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NFDeployment.ProtoReflect.Descriptor instead.
func (*NFDeployment) Descriptor() ([]byte, []int) {
	return file_nfdeployment_proto_rawDescGZIP(), []int{0}
}

func (x *NFDeployment) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *NFDeployment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NFDeployment) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type NFDeploymentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Condition string `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	Errormsg  string `protobuf:"bytes,2,opt,name=errormsg,proto3" json:"errormsg,omitempty"`
}

func (x *NFDeploymentResponse) Reset() {
	*x = NFDeploymentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nfdeployment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NFDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NFDeploymentResponse) ProtoMessage() {}

func (x *NFDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nfdeployment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NFDeploymentResponse.ProtoReflect.Descriptor instead.
func (*NFDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_nfdeployment_proto_rawDescGZIP(), []int{1}
}

func (x *NFDeploymentResponse) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *NFDeploymentResponse) GetErrormsg() string {
	if x != nil {
		return x.Errormsg
	}
	return ""
}

var File_nfdeployment_proto protoreflect.FileDescriptor

var file_nfdeployment_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6e, 0x66, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x0c, 0x4e,
	0x46, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61,
	0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x50, 0x0a,
	0x14, 0x4e, 0x46, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x73, 0x67, 0x32,
	0x93, 0x01, 0x0a, 0x0f, 0x4e, 0x46, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x50, 0x43, 0x12, 0x42, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x46, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4e, 0x46, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x46, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e,
	0x46, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_nfdeployment_proto_rawDescOnce sync.Once
	file_nfdeployment_proto_rawDescData = file_nfdeployment_proto_rawDesc
)

func file_nfdeployment_proto_rawDescGZIP() []byte {
	file_nfdeployment_proto_rawDescOnce.Do(func() {
		file_nfdeployment_proto_rawDescData = protoimpl.X.CompressGZIP(file_nfdeployment_proto_rawDescData)
	})
	return file_nfdeployment_proto_rawDescData
}

var file_nfdeployment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nfdeployment_proto_goTypes = []interface{}{
	(*NFDeployment)(nil),         // 0: proto.NFDeployment
	(*NFDeploymentResponse)(nil), // 1: proto.NFDeploymentResponse
}
var file_nfdeployment_proto_depIdxs = []int32{
	0, // 0: proto.NFDeploymentRPC.CreateUpdate:input_type -> proto.NFDeployment
	0, // 1: proto.NFDeploymentRPC.Delete:input_type -> proto.NFDeployment
	1, // 2: proto.NFDeploymentRPC.CreateUpdate:output_type -> proto.NFDeploymentResponse
	1, // 3: proto.NFDeploymentRPC.Delete:output_type -> proto.NFDeploymentResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nfdeployment_proto_init() }
func file_nfdeployment_proto_init() {
	if File_nfdeployment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nfdeployment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NFDeployment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nfdeployment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NFDeploymentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nfdeployment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nfdeployment_proto_goTypes,
		DependencyIndexes: file_nfdeployment_proto_depIdxs,
		MessageInfos:      file_nfdeployment_proto_msgTypes,
	}.Build()
	File_nfdeployment_proto = out.File
	file_nfdeployment_proto_rawDesc = nil
	file_nfdeployment_proto_goTypes = nil
	file_nfdeployment_proto_depIdxs = nil
}
