---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - workload.nephio.org
  resources:
  - nfdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.nephio.org
  resources:
  - nfdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - workload.nephio.org
  resources:
  - nfdeployments/status
  verbs:
  - get
  - patch
  - update
