---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.nfdeploy.nephio.io
  resources:
  - upfdeploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.nfdeploy.nephio.io
  resources:
  - upfdeploys/finalizers
  verbs:
  - update
- apiGroups:
  - batch.nfdeploy.nephio.io
  resources:
  - upfdeploys/status
  verbs:
  - get
  - patch
  - update
