# permissions for end users to edit upfdeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upfdeploy-editor-role
rules:
- apiGroups:
  - nfdeploy.nephio.io
  resources:
  - upfdeploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nfdeploy.nephio.io
  resources:
  - upfdeploys/status
  verbs:
  - get
