# permissions for end users to view upfdeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upfdeploy-viewer-role
rules:
- apiGroups:
  - nfdeploy.nephio.io
  resources:
  - upfdeploys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nfdeploy.nephio.io
  resources:
  - upfdeploys/status
  verbs:
  - get
